on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

name: Continuous integration

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all --all-features
      - run: |
          cargo test --manifest-path=clar2wasm/Cargo.toml --all-features -- --nocapture
          cargo test --manifest-path=tests/Cargo.toml --all-features -- --nocapture

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: |
          cargo fmt --manifest-path=clar2wasm/Cargo.toml  -- --check
          cargo fmt --manifest-path=tests/Cargo.toml -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: |
          cargo clippy --manifest-path=clar2wasm/Cargo.toml --no-deps --all-features --all-targets -- -D warnings
          cargo clippy --manifest-path=tests/Cargo.toml --no-deps --all-features --all-targets -- -D warnings
